const data = [
  {
    id: 1,
    heading: "The Khyber Himalayan Resort & Spa",
    address:
      "Hotel Khyber Rd, Forest Block, Jammu and Kashmir 193403 View on map",
    description:
      "A world away from the ordinary, this 85 key resort is framed at every vantage point by nature at its most spectacular. The world’s highest ski lift, the Gulmarg Gondola – which takes you to Kongdoori Mountain, is only a short walk away. Meadows and forests that have enchanted travellers for centuries wait to be explored by trekking enthusiasts and undying romantics. Clad in locally sourced pine and slate, the resort is built in a style true to the architectural heritage of Kashmir. In every way the indoors mirror the beauty of the outdoors. Speciality restaurants, a Sheesha lounge, a well-appointed spa and a heated swimming pool are amongst the necessary luxuries in place. Add to these other thoughtful additions like our children’s club, a mini theatre and a dedicated Activities Concierge and you will find The Khyber is a resort at par with the best in the world.",
    img: [
      "https://pix10.agoda.net/hotelImages/7540706/0/b500e9d817608060551ec995f22dce3c.jpg?ca=23&ce=0&s=1024x768",
      "https://i0.wp.com/www.traveldiaryparnashree.com/wp-content/uploads/2020/01/TheKhyberResort__5522.jpg?fit=799%2C600&ssl=1D",
      "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.expedia.co.in%2FSrinagar-Hotels-The-Khyber-Himalayan-Resort-Spa.h5502343.Hotel-Information&psig=AOvVaw3uk6TFL7qlJTY-hAhScm9Q&ust=1667726930551000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCJiox4vdlvsCFQAAAAAdAAAAABAP",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Fitness Center",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Parking",
      "Pool",
      "Restaurant,",
      "Smoking Room",
      "Spa & Sauna",
    ],
    hoteltheme: [
      "Business",
      "Classic",
      "Green",
      "Luxury",
      "Party",
      "Romantic",
      "Trendy",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 2,
    heading: "Fortune Resort Heevan",
    address: "Gupta Ganga, Nishat, Srinagar, Jammu and Kashmir",
    description:
      "Set in the picturesque valley of Srinagar with a magnificent view of the Zabarwan Mountains, Fortune Resort Heevan is a wonderful blend of traditional Kashmiri architecture with new-age conveniences. Fortune Resort Heevan, Srinagar offers 39 beautifully furnished rooms with an excellent range of modern guest facilities, landscaped gardens and a wide selection of culinary venues; which makes this resort in Srinagar an ideal retreat to experience the charm of Kashmir amidst warm Fortune hospitality. Srinagar, the summer capital of the Indian state of Jammu and Kashmir, lies in the Kashmir Valley on the banks of the Jhelum River. Srinagar famous for its historic gardens, indulgent houseboats and Kashmiri wooden mosques has been mesmerizing tourists since centuries and is a dream destination for many! Located minutes away from the Srinagar International Airport and popular tourist spots like Dal Lake, Chasm-e-Shahi, Shalimar Bagh, Tulip Garden and Nishat Bagh. Fortune Resort Heevan makes you feel the exuberance of the beautiful city of Srinagar with its ideal location.",
    img: [
      "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/166925616.jpg?k=1db94a2e28e7834ed6958912958ba24de9320804009adca8bc1a57f3efac64b9&o=&hp=1",
      "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/166929709.jpg?k=9a8f05bdeb1a85c1eccb98ee4d48fca2e9b523378044cb0183415ba6c9c27712&o=&hp=1",
      "https://t-cf.bstatic.com/xdata/images/hotel/max1024x768/166925969.jpg?k=5d3b096e3b26d1aa89d2aa9da351d2d03c24d95b1b27ed6f2e62bb5759e102a1&o=&hp=1",
    ],
    hotelfacilities: [
      "internet WIFI",
      "Air Conditioning",
      "Flat TV",
      "Pool",
      "Restaurant",
      "Smoking Room",
    ],
    hoteltheme: ["Business", "Geen", "luxury", "Mid-range", "Romantic"],
    rules: ["12:00 pm", "	12:00 pm"],
  },

  {
    id: 3,
    heading: "Royal Hillton",
    address: "Circuit Road Pahalgam Pahalgam Jammu and Kashmir, 192126",
    description:
      "Royal Hillton offers you comfort and luxury in the lap of great Himalayas. This beautiful and magnificent property spread on 2 acres is located in the heart of Pahalgam, Surrounded by undulating terrain of the vast snow Cladded Mountains, musical gushes of Lidder River and absolutely detached from the chaotic humdrum of the city life As one of the reputed hotels in Pahalgam, Royal Hillton is renowned for its world class room amenities with dedicated customer services. The Hotel offers 64 fully equipped and centrally heated premium rooms, and 8 Grand Royal suites which are exclusively, splendidly and lavishly designed",
    img: [
      "https://royalhillton.com/wp-content/uploads/2022/08/Highend-3605-1.webp",
      "https://royalhillton.com/wp-content/uploads/2022/08/Highend-3608.webp",
      "https://royalhillton.com/wp-content/uploads/2022/08/Highend-3602.webp",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Air Conditioning",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Pool",
    ],
    hoteltheme: [
      "Green",
      "Luxury",
      "Mid-range",
      "Romantic",
      "Standard",
      "",
      "",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 4,
    heading: "The Grand Dragon",
    address:
      "Union Territory Of Ladakh, Old Leh Rd, Sheynam, Leh, Jammu and Kashmir 194101",
    description:
      "Established in the year 2007, The Grand Dragon Ladakh, one of the first luxury hotels in Ladakh, is owned and operated by the Abdu family from Leh, who have more than 40 years of experience welcoming visitors to the beautiful region. It is decorated magnificently with handmade paintings by Gulam Mustafa (First modern Artist of Ladakh) around every corner, and fixtures that are reminiscent of royalty. The Grand Dragon Ladakh is the first hotel with a host of state of the art amenities, such as electronic key cards for the rooms and a baggage scanner, as well as their own sewage treatment facility. The entire facility is wheelchair accessible, for providing differently abled guests with a comfortable sojourn. The hotel is also centrally heated and solar powered, not only ensuring warmth but also ensuring that all our services are eco-friendly. The attention to detail offered by the associates, coupled with the magnificent views, will guarantee you take back home sweet memories.",
    img: [
      "https://www.thegranddragonladakh.com/assets/images/gl/3.jpg",
      "https://www.thegranddragonladakh.com/assets/images/gl/1.jpg",
      "https://www.thegranddragonladakh.com/assets/images/gl/26.jpg",
      "",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Restaurant",
      "",
      "",
      "",
    ],
    hoteltheme: [
      "Business",
      "Luxury",
      "Mid-range",
      "Party",
      "Romantic",
      "",
      "",
      "",
      "",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 5,
    heading: "Eden Resorts and Spa",
    address: "Rafting Point, Movera, Pahalgam, Jammu and Kashmir 192126",
    description:
      "Eden Resorts and Spa pristine beauty remains untouched by the chaos of the market and ensures that the best views are accorded  to Eden including the shimmering Lidder Our vision is to be the brand that guests love coming back to. We deliver this with a portfolio of service spectrums that resonate with superior standards in accommodation, cuisine, employee behaviour, and facilities. Eden Resorts and Spa is recognized for its spirit to serve and commitment to distinctiveness, which assures better guest satisfaction.Eden Resorts and Spa pristine beauty remains untouched by the chaos of the market and ensures that the best views are accorded  to Eden including the shimmering Lidder Our vision is to be the brand that guests love coming back to. We deliver this with a portfolio of service spectrums that resonate with superior standards in accommodation, cuisine, employee behaviour, and facilities. Eden Resorts and Spa is recognized for its spirit to serve and commitment to distinctiveness, which assures better guest satisfaction.Eden Resorts and Spa pristine beauty remains untouched by the chaos of the market and ensures that the best views are accorded  to Eden including the shimmering Lidder Our vision is to be the brand that guests love coming back to. We deliver this with a portfolio of service spectrums that resonate with superior standards in accommodation, cuisine, employee behaviour, and facilities. Eden Resorts and Spa is recognized for its spirit to serve and commitment to distinctiveness, which assures better guest satisfaction.Eden Resorts and Spa pristine beauty remains untouched by the chaos of the market and ensures that the best views are accorded  to Eden including the shimmering Lidder Our vision is to be the brand that guests love coming back to. We deliver this with a portfolio of service spectrums that resonate with superior standards in accommodation, cuisine, employee behaviour, and facilities. Eden Resorts and Spa is recognized for its spirit to serve and commitment to distinctiveness, which assures better guest satisfaction.",
    img: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/42/08/8a/facade.jpg?w=1000&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/69/7e/e5/eden-resorts.jpg?w=1000&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/09/dd/e7/9c/eden-resort-suites.jpg?w=700&h=-1&s=1",
      "",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Pool",
      "Restaurant",
      "Spa & Sauna",
      "",
    ],
    hoteltheme: [
      "Budget",
      "Mid-range",
      "Party",
      "Romantic",
      "",
      "",
      "",
      "",
      "",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 6,
    heading: "Jamal Resorts",
    address: "JCI Complex, Ishber, Nishat, Srinagar, Jammu and Kashmir 191121 ",
    description:
      "Jamal Resorts is promoted by The JCI (Jamal Carpet Industries) Group of companies, Srinagar. The pioneers in Manufacture, Retail and Exports of Carpets and Allied Crafts of Kashmir. Our vision remains to give the guests the finest experience of Kashmir through a quality resort with International service levels.",
    img: [
      "http://jamalresorts.com/temp/room-gallery-image-1.jpg",
      "http://jamalresorts.com/temp/room-gallery-image-4.jpg",
      "http://jamalresorts.com/temp/room-gallery-image-8.jpg",
      "http://jamalresorts.com/temp/room-gallery-image-9.jpg",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Flat Tv",
      "Internet – Wifi",
      "Parking",
      "Restaurant",
    ],
    hoteltheme: ["Business", "Classic", "Green", "Luxury", "Romantic"],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 7,
    heading: "Hotel Downtown",
    address: "Munawara Abad, Srinagar, Jammu and Kashmir 190001",
    description:
      "“Hotel Downtown” is literally located in the heart of city, around the prominent bustling street food junction, Khayam Chowk. Barely a 2 minutes ride away from the world famous “Dal Lake”, our hotel stands tall in the shadow of another great attraction “Hari Parbat”. Just steps away from major attraction of historical significance & electric market in Srinagar, our aristocratic property provides you the luxurious escape you have always been yearning for.",
    img: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1b/f7/d4/d0/exterior-night-light.jpg?w=1000&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/25/60/d3/b3/hotel-downtown.jpg?w=1000&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/21/56/e6/99/hotel-downtown.jpg?w=1000&h=-1&s=1",
      "",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Fitness Center",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Internet – Wifi",
      "Restaurant",
      "",
    ],
    hoteltheme: [
      "Budget",
      "Business",
      "Classic",
      "Mid-range",
      "Party",
      "Standard",
      "Trendy",
      "",
      "",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 8,
    heading: "Stok Palace Heritage",
    address: " No. 08, Post Box, Stok Palace, Stok, Jammu and Kashmir 194101",
    description:
      "Stok Palace Heritage is located in Leh, 16 km from Main Bazaar. This property also provides guests with a sun terrace. Shanti Stupa is 19 km away and Soma Gompa is 16 km from the hotel. The rooms are fitted with a private bathroom and free toiletries, and some units at the hotel have a balcony. The area is popular for cycling, and bike hire and car hire are available at Stok Palace Heritage. Namgyal Tsemo Gompa is 18 km from the accommodation. The nearest airport is Kushok Bakula Rimpochee Airport, 22 km from Stok Palace Heritage.",
    img: [
      "https://images.trvl-media.com/lodging/38000000/37840000/37837400/37837355/4fe1a6ba.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      "https://images.trvl-media.com/lodging/38000000/37840000/37837400/37837355/bff8debf.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      "https://images.trvl-media.com/lodging/38000000/37840000/37837400/37837355/c2f1f620.jpg?impolicy=resizecrop&rw=1200&ra=fit",
      "",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Restaurant",
      "",
      "",
      "",
    ],
    hoteltheme: [
      "Business",
      "Classic",
      "Luxury",
      "Romantic",
      "",
      "",
      "",
      "",
      "",
    ],
    rules: ["12:00 pm", "	12:00 pm"],
  },
  {
    id: 9,
    heading: "Hotel Highlands Park",
    address: "Church Road, Gulmarg, Jammu and Kashmir 193403",
    description:
      "from a long line of hoteliers. The Hotel remains a family run concern and is managed by the Major’s granddaughter and husband. Major Nedou’s army influence can be seen in the décor of the hotel as well as the staff uniforms. The hotel has a lot of artwork such as golfing paraphernalia, animal skins and traditional Kashmiri wall hangings that take you back to the time when Gulmarg first became a thriving summer destination for the well heeled. Presidents, Prime Ministers, visiting Royalty and Bollywood stars have all enjoyed the warm hospitality and old-world charm of this grand hotel. Highlands Park is a heritage property spread over eight acres of exquisite gardens in a majestic position on a spur in the center of Gulmarg.  It is surrounded by the peaks of the Apharwat range and has sweeping views across the valley to the greater Himalayas. The hotel consists of one central building and eight separate cottages that house the 35 character-filled rooms and suites. The grand central building which contains the reception, lounge and restaurant has uninterrupted views of the Gulmarg Golf course on one side and of Mt Apharwat on the other. The hotel was fully refurbished in 2013 and the rooms, Dining hall and Lounge were totally renovated without losing any of the character and old world charm that Highlands Park is famous for. The atmosphere is what really makes Highlands Park unique. The rooms are fantastic, the views awesome and the service exceptional",
    img: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/11/b5/5b/fd/hotel-highlands-park.jpg?w=1000&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/8a/4a/3b/hotel-highlands-park.jpg?w=800&h=-1&s=1",
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/10/8f/3a/7c/just-turn-the-photo-anti_rotated_270.jpg?w=1000&h=-1&s=1",
      "",
      "",
    ],
    hotelfacilities: [
      "Air Conditioning",
      "Airport Transport",
      "Flat Tv",
      "Heater",
      "Internet – Wifi",
      "Restaurant",
      "Smoking Room",
      "Romantic",
    ],
    hoteltheme: ["Business", "Green", "Luxury", "Party", "Trendy", "Romantic"],
    rules: ["12:00 pm", "	12:00 pm"],
  },
];

export default data;
